import type { BallFlightInput, BallFlightResult } from "../types";

// Physical constants
const GRAVITY = 9.81; // m/s^2
const AIR_DENSITY = 1.225; // kg/m^3 at sea level
const BALL_MASS = 0.04593; // kg (45.93g regulation golf ball)
const BALL_RADIUS = 0.02135; // m (42.7mm diameter)
const BALL_AREA = Math.PI * BALL_RADIUS * BALL_RADIUS; // cross-sectional area

// Aerodynamic coefficients based on golf ball research
// These vary with spin rate and Reynolds number
function getDragCoefficient(speed: number, spinRate: number): number {
  // Golf ball drag coefficient typically 0.24-0.28 at high speeds
  // Decreases slightly with higher spin due to boundary layer effects
  const baseCd = 0.21;
  // Add drag based on spin (Magnus effect creates wake turbulence)
  const spinDrag = (spinRate / 1000) * 0.011;
  const speedEffect = Math.max(0, (speed - 50) / 100) * 0.02;
  return baseCd + speedEffect + spinDrag;
}

function getLiftCoefficient(speed: number, spinRateRpm: number): number {
  // Lift coefficient based on spin parameter: S = (omega * r) / v
  // CL approximately equals 0.5 * S for golf balls (from wind tunnel data)
  const omega = (spinRateRpm * 2 * Math.PI) / 60; // rad/s
  const spinParameter = (omega * BALL_RADIUS) / Math.max(speed, 1);

  // Golf ball lift coefficient typically ranges 0.15-0.35
  // Based on Bearman & Harvey (1976) and other research
  const cl = 1.5 * spinParameter;
  return Math.min(cl, 0.27); // Cap at realistic maximum
}

// Unit conversions
function mphToMs(mph: number): number {
  return mph * 0.44704;
}

function msToMph(ms: number): number {
  return ms / 0.44704;
}

function metersToYards(m: number): number {
  return m * 1.09361;
}

function yardsToMeters(yards: number): number {
  return yards / 1.09361;
}

function degToRad(deg: number): number {
  return (deg * Math.PI) / 180;
}

function radToDeg(rad: number): number {
  return (rad * 180) / Math.PI;
}

export function calculateBallFlight(
  input: BallFlightInput,
  useMetric: boolean = false
): BallFlightResult {
  // Convert input to SI units (m/s)
  const ballSpeedMs = mphToMs(input.ballSpeed);
  const launchAngleRad = degToRad(input.launchAngle);
  const faceAngleRad = degToRad(input.clubFaceAngle);

  // Initial velocity components
  // Face angle affects initial direction
  let vx = ballSpeedMs * Math.cos(launchAngleRad) * Math.cos(faceAngleRad);
  let vy = ballSpeedMs * Math.sin(launchAngleRad);
  let vz = ballSpeedMs * Math.cos(launchAngleRad) * Math.sin(faceAngleRad);

  // Spin rates
  // Side spin is generated by face-to-path difference (about 70 rpm per degree)
  let backspinRpm = input.backspin;
  // D-Plane theory approximation: Side Spin ~= 300 * (Face - Path) for Driver, 150-200 for Irons
  // Using a dynamic multiplier based on launch angle (loft proxy)
  // Higher loft = Less side spin ratio, Lower loft = More side spin ratio
  // 10 deg loft ~ 300 multiplier, 30 deg loft ~ 100 multiplier
  const spinMultiplier = Math.max(100, 400 - input.launchAngle * 10);
  let sidespinRpm = (input.clubFaceAngle - input.clubPathAngle) * spinMultiplier;

  // Position (meters)
  let x = 0;
  let y = 0.01; // Start slightly above ground
  let z = 0;

  const trajectory: { x: number; y: number; z: number }[] = [];
  const dt = 0.005; // 5ms timestep for accuracy
  let time = 0;
  let maxHeight = 0;
  let landingAngle = 0;
  let lastVy = vy;

  // Simulate until ball hits ground (y <= 0) or timeout
  while (y >= 0 && time < 20) {
    // Record trajectory points (every 20ms for smooth visualization)
    if (Math.floor(time / 0.02) !== Math.floor((time - dt) / 0.02)) {
      trajectory.push({ x, y, z });
    }

    const speed = Math.sqrt(vx * vx + vy * vy + vz * vz);
    if (speed < 1) break;

    // Dynamic aerodynamic coefficients
    const cd = getDragCoefficient(speed, backspinRpm);
    const cl = getLiftCoefficient(speed, backspinRpm);

    // Side spin lift coefficient (Magnus effect is symmetric for spin axis)
    // Side force should be calculated using the same lift coefficient formula but with side spin
    // Removing the 0.6 dampener to allow full curvature
    const clSide = getLiftCoefficient(speed, Math.abs(sidespinRpm));

    // Aerodynamic forces
    const dynamicPressure = 0.5 * AIR_DENSITY * speed * speed;

    // Drag force (opposes velocity)
    const dragForce = cd * dynamicPressure * BALL_AREA;
    const dragAccel = dragForce / BALL_MASS;

    // Lift force from backspin (perpendicular to velocity, in vertical plane)
    const liftForce = cl * dynamicPressure * BALL_AREA;
    const liftAccel = liftForce / BALL_MASS;

    // Side force from sidespin (perpendicular to velocity, in horizontal plane)
    const sideForce = clSide * dynamicPressure * BALL_AREA;
    const sideAccel = sideForce / BALL_MASS;

    // Calculate unit vectors
    const horizontalSpeed = Math.sqrt(vx * vx + vz * vz);

    // Drag acts opposite to velocity direction
    const ax_drag = -dragAccel * (vx / speed);
    const ay_drag = -dragAccel * (vy / speed);
    const az_drag = -dragAccel * (vz / speed);

    // Lift from backspin acts perpendicular to velocity in the vertical plane
    // For forward motion, lift is primarily upward
    let ax_lift = 0;
    let ay_lift = 0;
    if (horizontalSpeed > 0.1) {
      // Lift perpendicular to velocity in xz-y plane
      const liftDirectionY = horizontalSpeed / speed;
      const liftDirectionX = -(vy * vx) / (speed * horizontalSpeed);
      // const liftDirectionZ = -(vy * vz) / (speed * horizontalSpeed);

      ax_lift = liftAccel * liftDirectionX;
      ay_lift = liftAccel * liftDirectionY;
    }

    // Total accelerations
    // IMPORTANT: In this physics engine:
    // x = forward, z = lateral.

    // Let's re-verify velocity components:
    // vx = speed * cos(launch) * cos(face) -> Primary Forward
    // vz = speed * cos(launch) * sin(face) -> Primary Lateral
    
    // So Forward is X-axis. Lateral is Z-axis.
    // Drag acts on X, Y, Z.
    // Lift (Backspin) acts on Y and X (backward tilt).
    // Side Force (Sidespin) acts on Z (lateral).
    
    // Calculate Side Force Vector (Perpendicular to velocity XZ plane)
    // Vector (vx, 0, vz) normalized is forward direction
    // Perpendicular is (-vz, 0, vx)
    
    const forwardSpeed = Math.max(0.001, Math.sqrt(vx * vx + vz * vz));
    const sideDirX = -vz / forwardSpeed; // Component affecting forward speed (turning reduces fwd speed)
    const sideDirZ = vx / forwardSpeed;  // Component affecting lateral position
    
    const ax_side = sideAccel * sideDirX * (sidespinRpm > 0 ? 1 : -1);
    const az_side_corr = sideAccel * sideDirZ * (sidespinRpm > 0 ? 1 : -1);

    const ax = ax_drag + ax_lift + ax_side;
    const ay = -GRAVITY + ay_drag + ay_lift;
    const az = az_drag + az_side_corr;

    // Update velocities (Euler integration)
    vx += ax * dt;
    vy += ay * dt;
    vz += az * dt;

    // Update positions
    x += vx * dt;
    y += vy * dt;
    z += vz * dt;

    // Track max height
    if (y > maxHeight) maxHeight = y;

    // Calculate landing angle when descending near ground
    if (y < 5 && vy < 0 && lastVy < 0) {
      const hSpeed = Math.sqrt(vx * vx + vz * vz);
      landingAngle = radToDeg(Math.atan2(-vy, hSpeed));
    }
    lastVy = vy;

    // Spin decay (approximately 1-2% per second)
    const spinDecay = 1 - 0.015 * dt;
    backspinRpm *= spinDecay;
    sidespinRpm *= spinDecay;

    time += dt;
  }

  // Add final position
  trajectory.push({ x, y: 0, z });

  // Calculate carry distance (where ball lands)
  const carryMeters = Math.max(0, x);
  const offlineMeters = z;

  // Estimate roll based on landing angle and speed
  // Steeper landing = less roll, faster landing = more roll
  const landingSpeed = Math.sqrt(vx * vx + vz * vz);
  const rollFactor = Math.max(0, 1 - landingAngle / 60) * (landingSpeed / 30);
  const rollMeters = Math.min(carryMeters * 0.15, rollFactor * 15);
  const totalMeters = carryMeters + rollMeters;

  // Convert trajectory for display
  const convertedTrajectory = trajectory.map((p) => ({
    x: useMetric ? p.x : metersToYards(p.x),
    y: useMetric ? p.y : metersToYards(p.y),
    z: useMetric ? p.z : metersToYards(p.z),
  }));

  return {
    carry: useMetric ? carryMeters : metersToYards(carryMeters),
    total: useMetric ? totalMeters : metersToYards(totalMeters),
    maxHeight: useMetric ? maxHeight : metersToYards(maxHeight),
    landingAngle: Math.round(landingAngle),
    offline: useMetric ? offlineMeters : metersToYards(offlineMeters),
    flightTime: Math.round(time * 10) / 10,
    trajectory: convertedTrajectory,
  };
}

export function getDefaultInputs(): BallFlightInput {
  return {
    ballSpeed: 150,
    clubSpeed: 100,
    launchAngle: 12,
    clubFaceAngle: 0,
    clubPathAngle: 0,
    backspin: 2500,
  };
}

export function getInputRanges() {
  return {
    ballSpeed: { min: 80, max: 200, step: 1 },
    clubSpeed: { min: 50, max: 140, step: 1 },
    launchAngle: { min: 0, max: 30, step: 0.5 },
    clubFaceAngle: { min: -10, max: 10, step: 0.5 },
    clubPathAngle: { min: -10, max: 10, step: 0.5 },
    backspin: { min: 1000, max: 5000, step: 100 },
  };
}

export { metersToYards, yardsToMeters, mphToMs, msToMph };
