import { GolfClub, ClubType } from "../entities/GolfClub";

type ClubSeed = Partial<GolfClub> & {
  name: string;
  brand: string;
  clubType: ClubType;
  price: number;
};

export const clubSeedData: ClubSeed[] = [
  // ============================================================
  // DRIVERS (~14)
  // ============================================================
  {
    name: "Qi10 Max Driver",
    brand: "TaylorMade",
    clubType: ClubType.DRIVER,
    price: 599.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular", "stiff"],
    loft: "9, 10.5, 12",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Maximum forgiveness driver with a large 460cc head and advanced carbon construction. Ideal for golfers seeking consistency off the tee.",
    imageUrl: "",
  },
  {
    name: "Qi10 Driver",
    brand: "TaylorMade",
    clubType: ClubType.DRIVER,
    price: 549.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "8, 9, 10.5",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "A versatile driver balancing distance and workability. Carbon crown and titanium face for explosive speed.",
    imageUrl: "",
  },
  {
    name: "Paradym Ai Smoke Max Driver",
    brand: "Callaway",
    clubType: ClubType.DRIVER,
    price: 599.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "9, 10.5, 12",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 9,
    description:
      "AI-designed face optimized for maximum forgiveness and straight ball flight. Great for players who want consistency.",
    imageUrl: "",
  },
  {
    name: "Paradym Ai Smoke Triple Diamond Driver",
    brand: "Callaway",
    clubType: ClubType.DRIVER,
    price: 599.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "8, 9, 10.5",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 4,
    distanceRating: 10,
    accuracyRating: 6,
    description:
      "A compact, low-spin driver built for elite players with fast swing speeds who want maximum workability.",
    imageUrl: "",
  },
  {
    name: "TSR3 Driver",
    brand: "Titleist",
    clubType: ClubType.DRIVER,
    price: 549.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "8, 9, 10",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 9,
    accuracyRating: 8,
    description:
      "Tour-level driver with adjustable CG track for precision shot shaping. Low spin for maximum distance.",
    imageUrl: "",
  },
  {
    name: "TSR2 Driver",
    brand: "Titleist",
    clubType: ClubType.DRIVER,
    price: 549.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "9, 10, 11",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "All-around performer combining speed, forgiveness, and adjustability. The most popular Titleist driver.",
    imageUrl: "",
  },
  {
    name: "G430 Max 10K Driver",
    brand: "Ping",
    clubType: ClubType.DRIVER,
    price: 599.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "9, 10.5, 12",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 10,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "The highest MOI driver from Ping with 10,000 g-cm2 moment of inertia. Ultimate forgiveness on off-center hits.",
    imageUrl: "",
  },
  {
    name: "G430 LST Driver",
    brand: "Ping",
    clubType: ClubType.DRIVER,
    price: 579.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "8, 9, 10.5",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Low-spin technology driver for players with high swing speeds seeking maximum distance with a penetrating flight.",
    imageUrl: "",
  },
  {
    name: "Aerojet Max Driver",
    brand: "Cobra",
    clubType: ClubType.DRIVER,
    price: 449.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "9, 10.5, 12",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Aerodynamic design for faster clubhead speed with draw-bias weighting for straighter shots. Great value.",
    imageUrl: "",
  },
  {
    name: "Aerojet Driver",
    brand: "Cobra",
    clubType: ClubType.DRIVER,
    price: 449.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "8, 9, 10.5",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Speed-optimized driver with PWR-BRIDGE weighting for low spin and explosive distance. Excellent value for money.",
    imageUrl: "",
  },
  {
    name: "ST-Z 230 Driver",
    brand: "Mizuno",
    clubType: ClubType.DRIVER,
    price: 499.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "9, 10.5",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Beta titanium face with Cortech Chamber for fast ball speed. A sleek, tour-inspired design with low spin.",
    imageUrl: "",
  },
  {
    name: "Launcher XL2 Driver",
    brand: "Cleveland",
    clubType: ClubType.DRIVER,
    price: 399.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular"],
    loft: "10.5, 12",
    swingSpeedRange: ["slow", "moderate"],
    forgivenessRating: 10,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "Ultra-lightweight design for maximum clubhead speed. Action Mass CB technology for effortless launch. Best value for beginners.",
    imageUrl: "",
  },

  // ============================================================
  // FAIRWAY WOODS (~12)
  // ============================================================
  {
    name: "Qi10 Max Fairway Wood",
    brand: "TaylorMade",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 349.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "3W (15), 5W (18), 7W (21)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Carbon construction fairway wood with maximum forgiveness. Easy to launch from any lie.",
    imageUrl: "",
  },
  {
    name: "Qi10 Tour Fairway Wood",
    brand: "TaylorMade",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 349.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "3W (13.5), 3HL (16.5)",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Compact head with low-spin profile for workability and control. Preferred by tour professionals.",
    imageUrl: "",
  },
  {
    name: "Paradym Ai Smoke Max Fairway",
    brand: "Callaway",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 349.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "3W (15), 5W (18), 7W (21), 9W (23)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 9,
    description:
      "AI-designed face with Jailbreak technology for speed and forgiveness. Easy to hit from fairway or rough.",
    imageUrl: "",
  },
  {
    name: "Paradym Ai Smoke Fairway",
    brand: "Callaway",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 349.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "3W (15), 5W (18)",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Mid-sized head with versatile performance. Balances distance with shot shaping ability.",
    imageUrl: "",
  },
  {
    name: "TSR2 Fairway Wood",
    brand: "Titleist",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 349.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "3W (15), 5W (18)",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 8,
    description:
      "Speed-enhanced fairway metal with improved face construction for faster ball speeds across the face.",
    imageUrl: "",
  },
  {
    name: "G430 Max Fairway Wood",
    brand: "Ping",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 329.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "3W (14.5), 5W (17.5), 7W (20.5), 9W (23.5)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "High-MOI fairway wood with spinsistency face technology. Consistent distance on every strike.",
    imageUrl: "",
  },
  {
    name: "Aerojet Max Fairway Wood",
    brand: "Cobra",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 279.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "3W (15), 5W (18), 7W (21)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 7,
    accuracyRating: 8,
    description:
      "PWR-BRIDGE weighting system with aerodynamic shape for easy launch. Outstanding value for beginners.",
    imageUrl: "",
  },
  {
    name: "ST-Z 230 Fairway Wood",
    brand: "Mizuno",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 299.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "3W (15), 5W (18)",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Maraging steel face with Wave technology sole for fast ball speed and low spin from the fairway.",
    imageUrl: "",
  },
  {
    name: "Launcher XL2 Fairway Wood",
    brand: "Cleveland",
    clubType: ClubType.FAIRWAY_WOOD,
    price: 249.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular"],
    loft: "3W (15), 5W (18), 7W (21)",
    swingSpeedRange: ["slow", "moderate"],
    forgivenessRating: 10,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "Ultra-lightweight and easy to hit. Ideal for slower swing speeds and beginners looking for consistent contact.",
    imageUrl: "",
  },

  // ============================================================
  // HYBRIDS (~10)
  // ============================================================
  {
    name: "Qi10 Max Rescue Hybrid",
    brand: "TaylorMade",
    clubType: ClubType.HYBRID,
    price: 299.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "3H (19), 4H (22), 5H (25), 6H (28)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Oversized head for maximum forgiveness. Carbon construction for higher launch and easier long shots.",
    imageUrl: "",
  },
  {
    name: "Qi10 Rescue Hybrid",
    brand: "TaylorMade",
    clubType: ClubType.HYBRID,
    price: 279.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "2H (17), 3H (19), 4H (22), 5H (25)",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Versatile rescue club that transitions smoothly between woods and irons. Low CG for easy launch.",
    imageUrl: "",
  },
  {
    name: "Paradym Ai Smoke Max Hybrid",
    brand: "Callaway",
    clubType: ClubType.HYBRID,
    price: 299.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "3H (19), 4H (22), 5H (25), 6H (28)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 9,
    description:
      "AI-optimized face design for consistent distance on off-center hits. Easy to launch from any lie.",
    imageUrl: "",
  },
  {
    name: "TSR2 Hybrid",
    brand: "Titleist",
    clubType: ClubType.HYBRID,
    price: 299.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "2H (17), 3H (19), 4H (21), 5H (24)",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 8,
    description:
      "Enhanced speed construction for maximum ball speed. Compact shape preferred by better players.",
    imageUrl: "",
  },
  {
    name: "G430 Hybrid",
    brand: "Ping",
    clubType: ClubType.HYBRID,
    price: 279.99,
    skillLevels: ["beginner", "intermediate", "advanced"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "3H (19), 4H (22), 5H (26), 6H (30)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Facewrap technology for faster ball speeds. High-density tungsten for high launch and forgiveness.",
    imageUrl: "",
  },
  {
    name: "Aerojet Max Hybrid",
    brand: "Cobra",
    clubType: ClubType.HYBRID,
    price: 229.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "3H (19), 4H (22), 5H (25), 6H (28)",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 7,
    accuracyRating: 8,
    description:
      "Offset design with draw bias for straighter shots. Hollow-body construction for easy launch.",
    imageUrl: "",
  },
  {
    name: "CLK Hybrid",
    brand: "Mizuno",
    clubType: ClubType.HYBRID,
    price: 249.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff"],
    loft: "3H (18), 4H (21), 5H (24)",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 7,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Wave technology sole for consistent face flex. Compact shape with a workable ball flight.",
    imageUrl: "",
  },
  {
    name: "Launcher XL2 Hybrid",
    brand: "Cleveland",
    clubType: ClubType.HYBRID,
    price: 199.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular"],
    loft: "3H (19), 4H (22), 5H (25), 6H (28), 7H (31)",
    swingSpeedRange: ["slow", "moderate"],
    forgivenessRating: 10,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "Ultra-lightweight design makes it the easiest hybrid to hit. Replace hard-to-hit long irons with confidence.",
    imageUrl: "",
  },

  // ============================================================
  // IRON SETS (~15)
  // ============================================================
  {
    name: "Qi Iron Set",
    brand: "TaylorMade",
    clubType: ClubType.IRON_SET,
    price: 999.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "5-PW, AW",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Cap Back design with SpeedFoam Air for explosive distance and forgiveness. Large sweet spot for consistent contact.",
    imageUrl: "",
  },
  {
    name: "P790 Iron Set",
    brand: "TaylorMade",
    clubType: ClubType.IRON_SET,
    price: 1399.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "4-PW",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 8,
    description:
      "Forged hollow-body construction with SpeedFoam Air. Players distance iron with tour-level aesthetics.",
    imageUrl: "",
  },
  {
    name: "P770 Iron Set",
    brand: "TaylorMade",
    clubType: ClubType.IRON_SET,
    price: 1499.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "3-PW",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "Compact forged iron with tungsten weighting. Precision feel and workability for skilled players.",
    imageUrl: "",
  },
  {
    name: "Paradym Ai Smoke Max Iron Set",
    brand: "Callaway",
    clubType: ClubType.IRON_SET,
    price: 999.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "5-PW, AW",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "AI-designed Flash Face for consistent ball speed. Oversized head with wide sole for easy launch.",
    imageUrl: "",
  },
  {
    name: "Apex Ai Smoke Iron Set",
    brand: "Callaway",
    clubType: ClubType.IRON_SET,
    price: 1399.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "4-PW",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 8,
    accuracyRating: 9,
    description:
      "Forged 1025 carbon steel with AI face. Premium feel with distance and precision for better players.",
    imageUrl: "",
  },
  {
    name: "Apex Pro Iron Set",
    brand: "Callaway",
    clubType: ClubType.IRON_SET,
    price: 1499.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "3-PW",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 4,
    distanceRating: 7,
    accuracyRating: 10,
    description:
      "Tour-validated forged iron with precise shaping. Maximum shot control and feedback for elite players.",
    imageUrl: "",
  },
  {
    name: "T150 Iron Set",
    brand: "Titleist",
    clubType: ClubType.IRON_SET,
    price: 1399.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "4-PW",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 7,
    accuracyRating: 10,
    description:
      "Tour iron with D18 high-density tungsten for precise CG placement. Preferred by tour professionals worldwide.",
    imageUrl: "",
  },
  {
    name: "T200 Iron Set",
    brand: "Titleist",
    clubType: ClubType.IRON_SET,
    price: 1299.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "4-PW",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 8,
    description:
      "Max Impact technology for speed and forgiveness in a players-distance design. Hollow body with polymer core.",
    imageUrl: "",
  },
  {
    name: "T350 Iron Set",
    brand: "Titleist",
    clubType: ClubType.IRON_SET,
    price: 999.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular", "stiff"],
    loft: "5-PW, AW",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 7,
    description:
      "Game improvement iron with large face and wide sole. Generous offset for straighter ball flight.",
    imageUrl: "",
  },
  {
    name: "G430 Iron Set",
    brand: "Ping",
    clubType: ClubType.IRON_SET,
    price: 937.50,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "senior", "regular", "stiff"],
    loft: "5-PW, UW",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 8,
    accuracyRating: 8,
    description:
      "Hyper 17-4 stainless steel face for faster ball speed. Custom tuning port for optimal sound and feel.",
    imageUrl: "",
  },
  {
    name: "i530 Iron Set",
    brand: "Ping",
    clubType: ClubType.IRON_SET,
    price: 1312.50,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "4-PW",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 9,
    accuracyRating: 8,
    description:
      "Hollow-body iron with maraging steel face. Players-distance design with exceptional feel.",
    imageUrl: "",
  },
  {
    name: "i230 Iron Set",
    brand: "Ping",
    clubType: ClubType.IRON_SET,
    price: 1200.00,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "3-PW",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "Forged 8620 carbon steel for exceptional feel. Compact blade-like profile for shot shaping.",
    imageUrl: "",
  },
  {
    name: "Air-X Iron Set",
    brand: "Cobra",
    clubType: ClubType.IRON_SET,
    price: 699.99,
    skillLevels: ["beginner"],
    shaftFlex: ["ladies", "senior", "regular"],
    loft: "5-PW, GW",
    swingSpeedRange: ["slow", "moderate"],
    forgivenessRating: 10,
    distanceRating: 7,
    accuracyRating: 8,
    description:
      "Ultra-lightweight design for maximum clubhead speed. Wide sole prevents digging. Best value for beginners.",
    imageUrl: "",
  },
  {
    name: "JPX925 Hot Metal Iron Set",
    brand: "Mizuno",
    clubType: ClubType.IRON_SET,
    price: 999.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular", "stiff"],
    loft: "5-PW, GW",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 8,
    distanceRating: 9,
    accuracyRating: 7,
    description:
      "Chromoly face for explosive speed. Seamless cup face for consistent distance across the face.",
    imageUrl: "",
  },
  {
    name: "JPX925 Forged Iron Set",
    brand: "Mizuno",
    clubType: ClubType.IRON_SET,
    price: 1299.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "4-PW",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 7,
    accuracyRating: 9,
    description:
      "Grain Flow Forged HD from a single billet of 1025E steel. The gold standard of forged feel.",
    imageUrl: "",
  },

  // ============================================================
  // WEDGES (~12)
  // ============================================================
  {
    name: "Milled Grind 4 Wedge",
    brand: "TaylorMade",
    clubType: ClubType.WEDGE,
    price: 179.99,
    skillLevels: ["intermediate", "advanced", "professional"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "46, 48, 50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 6,
    accuracyRating: 9,
    description:
      "Precision-milled sole with raw face for maximum spin. Tour-proven grind options for any condition.",
    imageUrl: "",
  },
  {
    name: "Hi-Toe 3 Wedge",
    brand: "TaylorMade",
    clubType: ClubType.WEDGE,
    price: 179.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular", "stiff"],
    loft: "50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 8,
    distanceRating: 6,
    accuracyRating: 8,
    description:
      "Full-face scoring lines for spin on any shot. Versatile sole grind for open-face shots around the green.",
    imageUrl: "",
  },
  {
    name: "Jaws Full Toe Wedge",
    brand: "Callaway",
    clubType: ClubType.WEDGE,
    price: 179.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "54, 56, 58, 60, 64",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "Aggressive JAWS grooves across the entire face. C-grind sole for versatility around the green.",
    imageUrl: "",
  },
  {
    name: "Jaws Raw Wedge",
    brand: "Callaway",
    clubType: ClubType.WEDGE,
    price: 179.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["stiff", "extra_stiff"],
    loft: "48, 50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 5,
    accuracyRating: 10,
    description:
      "Raw face for spin that increases over time. Offset groove-in-groove technology for maximum bite.",
    imageUrl: "",
  },
  {
    name: "Vokey SM10 Wedge",
    brand: "Titleist",
    clubType: ClubType.WEDGE,
    price: 189.99,
    skillLevels: ["intermediate", "advanced", "professional"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "46, 48, 50, 52, 54, 56, 58, 60, 62",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 6,
    accuracyRating: 10,
    description:
      "The most popular wedge on tour. Spin Milled grooves with multiple grind options for any playing style.",
    imageUrl: "",
  },
  {
    name: "Glide 4.0 Wedge",
    brand: "Ping",
    clubType: ClubType.WEDGE,
    price: 169.99,
    skillLevels: ["beginner", "intermediate", "advanced"],
    shaftFlex: ["regular", "stiff"],
    loft: "46, 48, 50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 8,
    distanceRating: 6,
    accuracyRating: 8,
    description:
      "Emery blast face for consistent spin. Four sole grinds to match your swing and turf conditions.",
    imageUrl: "",
  },
  {
    name: "Snakebite Wedge",
    brand: "Cobra",
    clubType: ClubType.WEDGE,
    price: 139.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular", "stiff"],
    loft: "50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["moderate", "fast"],
    forgivenessRating: 8,
    distanceRating: 6,
    accuracyRating: 7,
    description:
      "Snakebite grooves with multiple grinds for versatility. Great spin and value for recreational golfers.",
    imageUrl: "",
  },
  {
    name: "RTX 6 ZipCore Wedge",
    brand: "Cleveland",
    clubType: ClubType.WEDGE,
    price: 159.99,
    skillLevels: ["intermediate", "advanced", "professional"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "46, 48, 50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 6,
    accuracyRating: 9,
    description:
      "ZipCore technology lowers CG for higher launch with more spin. UltiZip grooves for maximum greenside control.",
    imageUrl: "",
  },
  {
    name: "CBX4 ZipCore Wedge",
    brand: "Cleveland",
    clubType: ClubType.WEDGE,
    price: 149.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["ladies", "regular", "stiff"],
    loft: "46, 48, 50, 52, 54, 56, 58",
    swingSpeedRange: ["slow", "moderate", "fast"],
    forgivenessRating: 9,
    distanceRating: 6,
    accuracyRating: 8,
    description:
      "Cavity-back wedge with wide sole for easy bunker play. ZipCore for spin without sacrificing forgiveness.",
    imageUrl: "",
  },
  {
    name: "T24 Wedge",
    brand: "Mizuno",
    clubType: ClubType.WEDGE,
    price: 149.99,
    skillLevels: ["intermediate", "advanced", "professional"],
    shaftFlex: ["regular", "stiff", "extra_stiff"],
    loft: "46, 48, 50, 52, 54, 56, 58, 60",
    swingSpeedRange: ["moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "Grain Flow Forged from 1025E boron steel. HydroFlow micro-grooves for wet and dry spin performance.",
    imageUrl: "",
  },

  // ============================================================
  // PUTTERS (~12)
  // ============================================================
  {
    name: "Spider GT Max Putter",
    brand: "TaylorMade",
    clubType: ClubType.PUTTER,
    price: 379.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 10,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "High-MOI mallet putter with True Path alignment. Steel-aluminum-tungsten construction for stability on off-center hits.",
    imageUrl: "",
  },
  {
    name: "Spider Tour Putter",
    brand: "TaylorMade",
    clubType: ClubType.PUTTER,
    price: 399.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 5,
    accuracyRating: 10,
    description:
      "Tour-proven mallet with Pure Roll insert for consistent speed. Compact design preferred by tour players.",
    imageUrl: "",
  },
  {
    name: "Odyssey Ai-ONE Mallet Putter",
    brand: "Callaway",
    clubType: ClubType.PUTTER,
    price: 299.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 10,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "AI-designed face insert for consistent ball speed across the face. High-MOI design with easy alignment.",
    imageUrl: "",
  },
  {
    name: "Odyssey Ai-ONE Blade Putter",
    brand: "Callaway",
    clubType: ClubType.PUTTER,
    price: 299.99,
    skillLevels: ["intermediate", "advanced", "professional"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "Classic blade shape with AI face insert. Clean look at address with improved feel for skilled players.",
    imageUrl: "",
  },
  {
    name: "Scotty Cameron Special Select Newport 2",
    brand: "Titleist",
    clubType: ClubType.PUTTER,
    price: 449.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["regular"],
    loft: "3.5",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 5,
    accuracyRating: 10,
    description:
      "Milled from 303 stainless steel. Classic blade design with precision weighting. The gold standard of putters.",
    imageUrl: "",
  },
  {
    name: "Scotty Cameron Phantom X Putter",
    brand: "Titleist",
    clubType: ClubType.PUTTER,
    price: 449.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular"],
    loft: "3.5",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 8,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "Multi-material mallet with solid face milling. High MOI with alignment aids for consistent strokes.",
    imageUrl: "",
  },
  {
    name: "Ping PLD Milled Anser Putter",
    brand: "Ping",
    clubType: ClubType.PUTTER,
    price: 499.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 6,
    distanceRating: 5,
    accuracyRating: 10,
    description:
      "Fully milled from 303 stainless steel. The iconic Anser design refined with precision CNC milling.",
    imageUrl: "",
  },
  {
    name: "Ping 2024 Tyne G Putter",
    brand: "Ping",
    clubType: ClubType.PUTTER,
    price: 299.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 10,
    distanceRating: 5,
    accuracyRating: 8,
    description:
      "High-MOI mallet with dual-durometer PEBAX insert for soft feel. Easy alignment with contrasting sightline.",
    imageUrl: "",
  },
  {
    name: "3D Printed Grandsport Putter",
    brand: "Cobra",
    clubType: ClubType.PUTTER,
    price: 349.99,
    skillLevels: ["beginner", "intermediate", "advanced"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 9,
    distanceRating: 5,
    accuracyRating: 8,
    description:
      "3D-printed lattice structure for optimized weight distribution. SIK face insert for consistent roll.",
    imageUrl: "",
  },
  {
    name: "Huntington Beach Soft Putter",
    brand: "Cleveland",
    clubType: ClubType.PUTTER,
    price: 149.99,
    skillLevels: ["beginner", "intermediate"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 8,
    distanceRating: 5,
    accuracyRating: 7,
    description:
      "Speed Optimized Face Technology for consistent distance control. Diamond CNC milled face. Excellent value.",
    imageUrl: "",
  },
  {
    name: "M-Craft OMOI Putter",
    brand: "Mizuno",
    clubType: ClubType.PUTTER,
    price: 349.99,
    skillLevels: ["advanced", "professional"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 5,
    distanceRating: 5,
    accuracyRating: 10,
    description:
      "Milled from a single block of 1025E mild carbon steel. Exceptionally soft feel with precise feedback.",
    imageUrl: "",
  },
  {
    name: "M-Craft V Putter",
    brand: "Mizuno",
    clubType: ClubType.PUTTER,
    price: 299.99,
    skillLevels: ["intermediate", "advanced"],
    shaftFlex: ["regular"],
    loft: "3",
    swingSpeedRange: ["slow", "moderate", "fast", "very_fast"],
    forgivenessRating: 7,
    distanceRating: 5,
    accuracyRating: 9,
    description:
      "Milled mallet design with adjustable sole weights. Forged from mild carbon steel for buttery feel.",
    imageUrl: "",
  },
];
